### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module

### ISSUE THREAD

**Issue by weiweihuanghuang** [imohanvadivel/variable-font-playground#3]
I'm having trouble building the package, when I run
`browserify --insert-globals -t brfs ./src/fontkit.js ./src/script.js -o ./main.js`
I get the following error:
```
Error: Can't walk dependency graph: Cannot find module '~/src/fontkit.js' from '~/src/_fake.js'
    required by ~/src/_fake.js
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:158:35
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:177:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:202:17)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:15:69
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by imohanvadivel** [comment]
Hey are you sure, that you'd installed all the dependencies?

After cloning the repo, run
`yarn install && yarn build`

That's it, then opening index.html in your local server will load the application.
Let me know, if this helps!
